# Generated by Django 4.1 on 2022-08-23 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('phone', models.IntegerField(max_length=20)),
                ('email', models.EmailField(max_length=100)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('blood_group', models.CharField(max_length=10)),
                ('district', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
